import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const starter={
 'lib/main.dart':"import 'package:flutter/material.dart';\n\nvoid main() => runApp(const MyApp());\n\nclass MyApp extends StatelessWidget {\n  const MyApp({super.key});\n  @override\n  Widget build(BuildContext context) => const MaterialApp(home: Scaffold(body: Center(child: Text('Generated by AI Flutter App Builder'))));\n}",
 'pubspec.yaml':"name: my_ai_app\ndescription: Generated by AI Flutter App Builder\nenvironment:\n  sdk: '>=3.0.0 <4.0.0'\ndependencies:\n  flutter:\n    sdk: flutter\nflutter:\n  uses-material-design: true",
 'README.md':"# My AI App\n\nGenerated by AI Flutter App Builder."
};

function FlutterPreview({files}){
 const dart=files['lib/main.dart']||'';
 const text=(dart.match(/Text\(['"]([^'"]+)/)?.[1])||'Generated by AI Flutter App Builder';
 const title=(dart.match(/title:\s*['"]([^'"]+)/)?.[1])||'My AI App';
 return <div className="preview-wrap">
  <div className="preview-top"><span>APP PREVIEW</span><small>Flutter • live</small></div>
  <div className="phone iphone"><div className="phone-notch"></div><div className="phone-screen">
   <div className="flutter-status"><span>9:41</span><span>● ◔ ▮</span></div>
   <div className="flutter-appbar">{title}</div>
   <div className="flutter-body"><div className="flutter-card"><div className="flutter-icon">✦</div><h3>{text}</h3><p>Generated by your AI Flutter Builder</p><button>Get Started</button></div></div>
   <div className="flutter-nav"><span>⌂</span><span>◯</span><span>⚙</span></div>
  </div></div>
  <div className="preview-note">Preview updates from <b>lib/main.dart</b>. Real APK builds run through the Flutter build runner.</div>
 </div>;
}

function App(){
 const [projects,setProjects]=useState(()=>JSON.parse(localStorage.getItem('projects')||'[]'));
 const [active,setActive]=useState(()=>localStorage.getItem('active')||'');
 const [files,setFiles]=useState(()=>JSON.parse(localStorage.getItem('files')||'null')||starter);
 const [builds,setBuilds]=useState(()=>JSON.parse(localStorage.getItem('builds')||'[]'));
 const [tab,setTab]=useState('dashboard'),[prompt,setPrompt]=useState(''),[file,setFile]=useState('lib/main.dart');
 const [chat,setChat]=useState([{r:'AI',t:'Tell me what app you want to build. I’ll ask a few questions first, then create a preview before you build the APK.'}]);
 const [aiBusy,setAiBusy]=useState(false);
 const [requirements,setRequirements]=useState([]);
 const apiUrl=window.location.origin;
 useEffect(()=>localStorage.setItem('projects',JSON.stringify(projects)),[projects]);
 useEffect(()=>localStorage.setItem('active',active),[active]);
 useEffect(()=>localStorage.setItem('files',JSON.stringify(files)),[files]);
 useEffect(()=>localStorage.setItem('builds',JSON.stringify(builds)),[builds]);

 const project=projects.find(p=>p.id===active);

 function explainError(e,status,requestId){
  const m=String(e?.message||e||'Unknown error');
  if(m==='Failed to fetch'||m.includes('NetworkError')||m.includes('Load failed')) return `AI CONNECTION FAILED\n\nThe browser could not reach the AI backend at ${apiUrl}.\n\nOpen ${apiUrl}/health. If it does not load, the Render service is unavailable. If it loads, confirm GROQ_API_KEY is set in Render Environment and redeploy. Then try again.`;
  if(status===401||m.toLowerCase().includes('invalid api key')||m.toLowerCase().includes('authentication')) return 'GROQ AUTHENTICATION ERROR\\n\\nGroq rejected the API key. Check GROQ_API_KEY in Render Environment.';
  if(status===429||m.toLowerCase().includes('rate limit')) return 'GROQ RATE LIMIT\\n\\nThe AI provider temporarily rate-limited this request. Wait and try again.';
  if(status===404||m.toLowerCase().includes('model')) return 'GROQ MODEL ERROR\\n\\nThe configured model may be unavailable. Check GROQ_MODEL in Render Environment.';
  return m+(requestId?'\\n\\nRequest ID: '+requestId:'');
}

async function generate(d,historyOverride){
  setAiBusy(true);
  try{
   const history=historyOverride||chat;
   let r;
   try{
    r=await fetch(apiUrl+'/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:d,conversation:history.map(m=>({role:m.r==='You'?'user':'assistant',content:m.t})),files:Object.entries(filesOverride).map(([path,content])=>({path,content}))})});
   }catch(e){ throw Object.assign(new Error(explainError(e)),{network:true}); }
   let data={};
   try{
    const ct=r.headers.get('content-type')||'';
    data=ct.includes('application/json')?await r.json():{error:await r.text()};
   }catch(e){ throw new Error('AI BACKEND RESPONSE ERROR\\n\\nThe server returned HTTP '+r.status+' but the response could not be read. Check Render logs.'); }
   if(!r.ok) throw Object.assign(new Error(data.error||'AI request failed'),{status:r.status,requestId:data.requestId});
   if(data.mode==='questions'){
    const qs=Array.isArray(data.questions)?data.questions.slice(0,2):[];
    setRequirements(qs);
    setChat(c=>[...c,{r:'AI',t:data.message||'I only need one or two details before I build it.'},...qs.map((q,i)=>({r:'AI',t:`Question ${i+1}: ${q}`}))]);
   }else{
    const next={...files};(data.files||[]).forEach(x=>{next[x.path]=x.content});
    setFiles(next);setRequirements([]);
    setChat(c=>[...c,{r:'AI',t:data.message||'I created the app preview. Review it before building the APK.'}]);
    setProjects(x=>x.map(v=>v.id===active?{...v,status:'ready',updatedAt:new Date().toISOString()}:v));
    setTab('builder');
   }
   return data;
  }catch(e){
   setChat(c=>[...c,{r:'AI',t:explainError(e,e.status,e.requestId)}]);
   return null;
  }finally{setAiBusy(false);}
 }

 async function createProject(){
  const d=prompt.trim()||'Build a modern Flutter application.';
  const p={id:crypto.randomUUID(),name:d.slice(0,36),description:d,status:'designing',updatedAt:new Date().toISOString()};
  setProjects(x=>[p,...x]);setActive(p.id);setTab('dashboard');
  const first=[{r:'You',t:d},{r:'AI',t:'I’ll ask a few questions before generating the app.'}];
  setChat(first);setPrompt('');
  const result=await generate(d,first);
  if(result?.mode==='generated' && /\b(start|build|create|make|generate)\b/i.test(d)){
   const next={...files};(result.files||[]).forEach(x=>{next[x.path]=x.content});
   setTimeout(()=>build('apk',p,next),0);
  }
 }

 async function build(format,projectOverride=project,filesOverride=files){
  if(!projectOverride||aiBusy)return;
  const localId=crypto.randomUUID();
  const job={id:localId,projectId:projectOverride.id,projectName:projectOverride.name,format,status:'queued',message:'Build queued.',createdAt:new Date().toISOString()};
  setBuilds(x=>[job,...x]);setTab('builds');
  try{
   const r=await fetch(apiUrl+'/api/build',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({format,projectName:projectOverride.name,files:Object.entries(filesOverride).map(([path,content])=>({path,content}))})});
   const data=await r.json();
   if(!r.ok)throw new Error(data.error||'Build request failed');
   setBuilds(x=>x.map(b=>b.id===localId?{...b,remoteId:data.id,status:data.status||'queued',message:'Build submitted to Flutter runner.'}:b));
   if(data.id)pollBuild(localId,data.id);
  }catch(e){setBuilds(x=>x.map(b=>b.id===localId?{...b,status:'failed',message:e.message}:b));}
 }
 async function pollBuild(localId,remoteId){
  for(let i=0;i<120;i++){
   await new Promise(r=>setTimeout(r,3000));
   try{
    const r=await fetch(apiUrl+'/api/build/'+encodeURIComponent(remoteId));const data=await r.json();
    if(!r.ok)throw new Error(data.error||'Status request failed');
    const status=data.status==='successful'?'success':data.status;
    setBuilds(x=>x.map(b=>b.id===localId?{...b,status,message:data.error||b.message,artifactReady:Boolean(data.artifactReady)}:b));
    if(status==='success'||status==='failed')return;
   }catch(e){setBuilds(x=>x.map(b=>b.id===localId?{...b,status:'failed',message:e.message}:b));return;}
  }
  setBuilds(x=>x.map(b=>b.id===localId?{...b,status:'failed',message:'Build status polling timed out.'}:b));
 }
 async function send(){const q=prompt.trim();if(!q||aiBusy)return;const next=[...chat,{r:'You',t:q},{r:'AI',t:'Thinking with Groq…'}];setChat(next);setPrompt('');const result=await generate(q,next);if(result?.mode==='generated'&&project&&/\b(start|build|create|make|generate)\b/i.test(q)){const nextFiles={...files};(result.files||[]).forEach(x=>{nextFiles[x.path]=x.content});setTimeout(()=>build('apk',project,nextFiles),0);}}

 return <div className="app chatgpt-shell">
  <aside className="sidebar">
   <div className="brand"><strong>✦ AI Flutter</strong><small>App Builder</small></div>
   <button className="newchat" onClick={()=>{setTab('dashboard');setPrompt('');setChat([{r:'AI',t:'What do you want to build today? I can generate and modify Flutter source code.'}]);}}>＋ New chat</button>
   <nav>{[['dashboard','⌂','Chat'],['projects','▣','Projects'],['builder','⌘','Builder'],['builds','▶','Builds']].map(x=><button className={tab===x[0]?'nav active':'nav'} onClick={()=>setTab(x[0])} key={x[0]}><span>{x[1]}</span>{x[2]}</button>)}</nav>
   <div className="history"><small>RECENT</small>{projects.slice(0,6).map(p=><button key={p.id} onClick={()=>{setActive(p.id);setTab('builder')}}>{p.name}</button>)}</div>
   <div className="runner">● AI ENGINE<br/><small>{apiUrl?'Connected to Groq backend':'Backend not configured'}</small></div>
  </aside>
  <main className="chat-main">
   <header><div><strong>AI Flutter Builder</strong><small>Build apps with AI</small></div><button className="model">Groq ▾</button></header>
   {tab==='dashboard'&&<section className="chat-home">
    <div className="welcome"><div className="logo-mark">✦</div><h1>What can I build for you?</h1><p>Describe your idea. I’ll ask questions, design it with you, show a preview, and only build the APK when you’re ready.</p></div>
    <div className="conversation">{chat.map((m,i)=><div className={m.r==='You'?'bubble user':'bubble ai'} key={i}><div className="avatar">{m.r==='You'?'Y':'✦'}</div><div><strong>{m.r==='You'?'You':'AI Flutter'}</strong><p>{m.t}</p></div></div>)}</div>
    <div className="composer"><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')createProject()}} placeholder="Describe the Flutter app you want to build…"/><div className="composer-bottom"><span>{requirements.length?'Answer the questions above. I’ll update the design before building.':'AI will ask questions, create a preview, then let you build the APK.'}</span><button disabled={aiBusy} onClick={createProject}>{aiBusy?'Generating…':'↑'}</button></div></div>
    <div className="suggestions">{['Build a WhatsApp-style messenger','Create an AI chatbot','Build an e-commerce app','Make a food delivery app'].map(x=><button key={x} onClick={()=>setPrompt(x+' with a polished modern mobile UI.')}>{x} <span>→</span></button>)}</div>
   </section>}
   {tab==='projects'&&<section><h2>Your projects</h2><p className="muted">Open a project to continue coding with the AI assistant.</p>{projects.map(p=><Card p={p} open={()=>{setActive(p.id);setTab('builder')}} key={p.id}/>)}{!projects.length&&<div className="empty">No projects yet. Start a new chat.</div>}</section>}
   {tab==='builder'&&<section className="builder">{!project?<div className="empty">Select a project first.</div>:<>
    <div className="bar"><span className="badge">{project.status}</span><span className="preview-ready">● Preview ready</span><button onClick={()=>setTab('builder')}>Preview</button><button onClick={()=>build('apk')}>Build APK</button><button onClick={()=>build('aab')}>Build AAB</button></div>
    <div className="workspace">
     <div className="ide"><div className="files"><b>FILES</b>{Object.keys(files).map(f=><button className={file===f?'selected':''} onClick={()=>setFile(f)} key={f}>{f}</button>)}</div><div className="editor"><div>{file}<span>● Saved</span></div><textarea value={files[file]||''} onChange={e=>setFiles({...files,[file]:e.target.value})}/></div></div>
     <FlutterPreview files={files}/>
     <div className="assistant"><b>AI ASSISTANT</b><div className="chat">{chat.map((m,i)=><div className="msg" key={i}><strong>{m.r}</strong><p>{m.t}</p></div>)}</div><div className="chatbox"><input value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Ask AI to change the app..."/><button onClick={send}>↑</button></div></div>
    </div>
   </>}</section>}
   {tab==='builds'&&<BuildHistory builds={builds} projects={projects} apiUrl={apiUrl}/>}
  </main>
 </div>
}
function BuildHistory({builds,projects,apiUrl}){const total=builds.length;const success=builds.filter(b=>b.status==='success').length;const failed=builds.filter(b=>b.status==='failed').length;return <section className="build-history"><div className="history-head"><div><h2>Build history</h2><p className="muted">Track every APK and AAB build from your projects.</p></div><div className="history-count">{total} build{total===1?'':'s'}</div></div><div className="build-stats"><div><b>{total}</b><span>Total builds</span></div><div><b>{success}</b><span>Successful</span></div><div><b>{failed}</b><span>Failed</span></div></div>{builds.length?<div className="build-list">{builds.map(b=><div className="build-row" key={b.id}><div className="build-type">{b.format==='apk'?'APK':'AAB'}</div><div className="build-info"><strong>{b.projectName||projects.find(p=>p.id===b.projectId)?.name||'Flutter project'}</strong><span>{new Date(b.createdAt).toLocaleString()}</span>{b.message&&<small>{b.message}</small>}</div><span className={"badge "+(b.status==='success'?'success':b.status==='failed'?'failed':'yellow')}>{b.status}</span>{b.status==='success'&&b.artifactReady&&b.remoteId?<a className="build-download" href={apiUrl+'/api/build/'+encodeURIComponent(b.remoteId)+'/artifact'} download>{b.format==='aab'?'Download AAB':'Download APK'}</a>:<button className="build-more" title="Build details">⋯</button>}</div>)}</div>:<div className="empty"><div className="empty-icon">◈</div><h3>No builds yet</h3><p>Create a project and choose Build APK or Build AAB to start your build history.</p></div>}</section>}

function Card({p,open}){return <div className="card"><div className="icon">⌁</div><div><h3>{p.name}</h3><p>{p.description}</p><small className="badge">{p.status}</small></div><button onClick={open}>Open →</button></div>}

createRoot(document.getElementById('root')).render(<App/>);