import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const starter={
 'lib/main.dart':"import 'package:flutter/material.dart';\n\nvoid main() => runApp(const MyApp());\n\nclass MyApp extends StatelessWidget {\n  const MyApp({super.key});\n  @override\n  Widget build(BuildContext context) => const MaterialApp(home: Scaffold(body: Center(child: Text('Generated by AI Flutter App Builder'))));\n}",
 'pubspec.yaml':"name: my_ai_app\ndescription: Generated by AI Flutter App Builder\nenvironment:\n  sdk: '>=3.0.0 <4.0.0'\ndependencies:\n  flutter:\n    sdk: flutter\nflutter:\n  uses-material-design: true",
 'README.md':"# My AI App\n\nGenerated by AI Flutter App Builder."
};

function App(){
 const [projects,setProjects]=useState(()=>JSON.parse(localStorage.getItem('projects')||'[]'));
 const [active,setActive]=useState(()=>localStorage.getItem('active')||'');
 const [files,setFiles]=useState(()=>JSON.parse(localStorage.getItem('files')||'null')||starter);
 const [builds,setBuilds]=useState(()=>JSON.parse(localStorage.getItem('builds')||'[]'));
 const [tab,setTab]=useState('dashboard'),[prompt,setPrompt]=useState(''),[file,setFile]=useState('lib/main.dart');
 const [chat,setChat]=useState([{r:'AI',t:'Describe the Flutter app you want to build. Groq will generate real project files through the secure backend.'}]);
 const [aiBusy,setAiBusy]=useState(false); const rawApiUrl=import.meta.env.VITE_AI_API_URL||''; const apiUrl=(rawApiUrl ? (rawApiUrl.startsWith('http')?rawApiUrl:'https://'+rawApiUrl).replace(/\/$/,'') : window.location.origin);
 useEffect(()=>localStorage.setItem('projects',JSON.stringify(projects)),[projects]);
 useEffect(()=>localStorage.setItem('active',active),[active]); useEffect(()=>localStorage.setItem('files',JSON.stringify(files)),[files]); useEffect(()=>localStorage.setItem('builds',JSON.stringify(builds)),[builds]);
 const project=projects.find(x=>x.id===active);
 async function createProject(){const d=prompt.trim()||'Build a modern Flutter application.';const p={id:crypto.randomUUID(),name:d.slice(0,36),description:d,status:'generating',updatedAt:new Date().toISOString()};setProjects(x=>[p,...x]);setActive(p.id);setTab('builder');setAiBusy(true);setChat([{r:'You',t:d},{r:'AI',t:'Generating your Flutter project with Groq…'}]);try{if(!apiUrl)throw new Error('AI backend is not configured. Set VITE_AI_API_URL.');const r=await fetch(apiUrl+'/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:d,files:Object.entries(starter).map(([path,content])=>({path,content}))})});const data=await r.json();if(!r.ok)throw new Error(data.error||'AI generation failed');const next={...starter};(data.files||[]).forEach(x=>{next[x.path]=x.content});setFiles(next);setProjects(x=>x.map(v=>v.id===p.id?{...v,status:'ready',updatedAt:new Date().toISOString()}:v));setChat([{r:'AI',t:data.message||'Project generated successfully with Groq.'}]);}catch(e){setProjects(x=>x.map(v=>v.id===p.id?{...v,status:'draft'}:v));setChat(c=>[...c,{r:'AI',t:e.message}]);}finally{setAiBusy(false);}}
 function build(format){if(!project)return;setBuilds([{id:crypto.randomUUID(),projectId:project.id,format,status:'queued',message:'External Flutter build runner is not configured.',createdAt:new Date().toISOString()},...builds]);setTab('builds');}
 async function send(){const q=prompt.trim();if(!q||aiBusy)return;setAiBusy(true);setChat(c=>[...c,{r:'You',t:q},{r:'AI',t:'Thinking with Groq…'}]);setPrompt('');try{if(!apiUrl)throw new Error('AI backend is not configured.');const r=await fetch(apiUrl+'/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:q,files:Object.entries(files).map(([path,content])=>({path,content}))})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Groq request failed');const next={...files};(data.files||[]).forEach(x=>next[x.path]=x.content);setFiles(next);setChat(c=>[...c.slice(0,-1),{r:'AI',t:data.message||'Changes generated and applied.'}]);}catch(e){setChat(c=>[...c.slice(0,-1),{r:'AI',t:e.message}]);}finally{setAiBusy(false);}}
 return <div className="app chatgpt-shell">
  <aside className="sidebar">
    <div className="brand"><strong>✦ AI Flutter</strong><small>App Builder</small></div>
    <button className="newchat" onClick={()=>{setTab('dashboard');setPrompt('');setChat([{r:'AI',t:'What do you want to build today? I can generate and modify Flutter source code.'}]);}}>＋ New chat</button>
    <nav>{[['dashboard','⌂','Chat'],['projects','▣','Projects'],['builder','⌘','Builder'],['builds','▶','Builds']].map(x=><button className={tab===x[0]?'nav active':'nav'} onClick={()=>setTab(x[0])} key={x[0]}><span>{x[1]}</span>{x[2]}</button>)}</nav>
    <div className="history"><small>RECENT</small>{projects.slice(0,6).map(p=><button key={p.id} onClick={()=>{setActive(p.id);setTab('builder')}}>{p.name}</button>)}</div>
    <div className="runner">● AI ENGINE<br/><small>{apiUrl?'Connected to Groq backend':'Backend not configured'}</small></div>
  </aside>
  <main className="chat-main">
    <header><div><strong>AI Flutter Builder</strong><small>Build apps with AI</small></div><button className="model">Groq ▾</button></header>
    {tab==='dashboard'&&<section className="chat-home">
      <div className="welcome"><div className="logo-mark">✦</div><h1>What can I build for you?</h1><p>Describe an app and I’ll generate the Flutter project, source files, and UI.</p></div>
      <div className="conversation">{chat.map((m,i)=><div className={m.r==='You'?'bubble user':'bubble ai'} key={i}><div className="avatar">{m.r==='You'?'Y':'✦'}</div><div><strong>{m.r==='You'?'You':'AI Flutter'}</strong><p>{m.t}</p></div></div>)}</div>
      <div className="composer"><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')createProject()}} placeholder="Describe the Flutter app you want to build…"/><div className="composer-bottom"><span>AI can generate real Flutter source files</span><button disabled={aiBusy} onClick={createProject}>{aiBusy?'Generating…':'↑'}</button></div></div>
      <div className="suggestions">{['Build a WhatsApp-style messenger','Create an AI chatbot','Build an e-commerce app','Make a food delivery app'].map(x=><button key={x} onClick={()=>setPrompt(x+' with a polished modern mobile UI.')}>{x} <span>→</span></button>)}</div>
    </section>}
    {tab==='projects'&&<section><h2>Your projects</h2><p className="muted">Open a project to continue coding with the AI assistant.</p>{projects.map(p=><Card p={p} open={()=>{setActive(p.id);setTab('builder')}} key={p.id}/>)}{!projects.length&&<div className="empty">No projects yet. Start a new chat.</div>}</section>}
    {tab==='builder'&&<section className="builder">{!project?<div className="empty">Select a project first.</div>:<><div className="bar"><span className="badge">{project.status}</span><button onClick={()=>build('apk')}>Build APK</button><button onClick={()=>build('aab')}>Build AAB</button></div><div className="ide"><div className="files"><b>FILES</b>{Object.keys(files).map(f=><button className={file===f?'selected':''} onClick={()=>setFile(f)} key={f}>{f}</button>)}</div><div className="editor"><div>{file}<span>● Saved</span></div><textarea value={files[file]||''} onChange={e=>setFiles({...files,[file]:e.target.value})}/></div><div className="assistant"><b>AI ASSISTANT</b><div className="chat">{chat.map((m,i)=><div className="msg" key={i}><strong>{m.r}</strong><p>{m.t}</p></div>)}</div><div className="chatbox"><input value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Ask AI to change the app..."/><button onClick={send}>↑</button></div></div></div></>}</section>}
    {tab==='builds'&&<section><h2>Build jobs</h2><p className="muted">Only an external Flutter runner can produce real APK/AAB artifacts.</p>{builds.map(b=><div className="build" key={b.id}><strong>{b.format.toUpperCase()}</strong><span className="badge yellow">{b.status}</span><p>{b.message}</p><small>{new Date(b.createdAt).toLocaleString()}</small></div>)}{!builds.length&&<div className="empty">No build jobs yet.</div>}</section>}
  </main>
 </div>
}
function Card({p,open}){return <div className="card"><div className="icon">⌁</div><div><h3>{p.name}</h3><p>{p.description}</p><small className="badge">{p.status}</small></div><button onClick={open}>Open →</button></div>}
createRoot(document.getElementById('root')).render(<App/>);